### ISSUE TITLE
plz don't do this

### ISSUE THREAD

**Issue by Blind4Basics** [AnangAyman/Python_codewars#1]
Hello,

Thanks for being a Codewars member. If you actually plan on putting solutions in this repo, please make it private. By adding your solutions to Github you are adding to the possibility that Google search will surface your solutions to others. For more information you can read the last paragraph of the [rules section in Codewars code of conduct](https://docs.codewars.com/community/rules#rules). If you don’t want to make the repository private, then please remove any reference to Codewars or the names or IDs of the kata you add solutions for. This way it won’t be easy for search engines to surface your solutions. 

Thx

**Comment by AnangAyman** [comment]
My apologies, I just learned about Github recently. I will remove it straight away.
